select CustomerAccount, INVOICEACCOUNT, DATAAREAID from CUSTCUSTOMERV3ENTITY
where INVOICEACCOUNT = CUSTOMERACCOUNT

update CUSTCUSTOMERV3ENTITY
	set INVOICEACCOUNT = ''
where INVOICEACCOUNT = CUSTOMERACCOUNT
