--0 Global check
select itm.ITEMID, itm.UNITID, itm.DATAAREAID, rp.ITEMNUMBER, rp.INVENTORYUNITSYMBOL, rp.SALESUNITSYMBOL, rp.PURCHASEUNITSYMBOL, rp.BOMUNITSYMBOL, rp.PRODUCTNUMBER, rp.PRODUCTSEARCHNAME, rp.DATAAREAID  from InventTableModule itm
inner join ECORESRELEASEDPRODUCTV2ENTITY rp on itm.ITEMID = rp.ITEMNUMBER and itm.DATAAREAID = rp.DATAAREAID
where  rp.INVENTORYUNITSYMBOL = '' or rp.SALESUNITSYMBOL = '' or rp.PURCHASEUNITSYMBOL = ''



--1 INVENTORYUNITSYMBOL from PURCHASEUNITSYMBOL
select itm.ITEMID, itm.UNITID, itm.DATAAREAID, rp.ITEMNUMBER, rp.INVENTORYUNITSYMBOL, rp.SALESUNITSYMBOL, rp.PURCHASEUNITSYMBOL, rp.PRODUCTNUMBER, rp.PRODUCTSEARCHNAME, rp.DATAAREAID  from InventTableModule itm
inner join ECORESRELEASEDPRODUCTV2ENTITY rp on itm.ITEMID = rp.ITEMNUMBER and itm.DATAAREAID = rp.DATAAREAID
where rp.INVENTORYUNITSYMBOL = ''  and rp.PURCHASEUNITSYMBOL != ''


Update itm
	set itm.UnitId = rp.PURCHASEUNITSYMBOL
from InventTableModule itm
inner join ECORESRELEASEDPRODUCTV2ENTITY rp on itm.ITEMID = rp.ITEMNUMBER and itm.DATAAREAID = rp.DATAAREAID
where rp.INVENTORYUNITSYMBOL = ''  and rp.PURCHASEUNITSYMBOL != ''


--2  Check that all items could be assigned to EA UOM   INVENTORYUNITSYMBOL
select itm.ITEMID, itm.UNITID, itm.DATAAREAID, rp.ITEMNUMBER, rp.INVENTORYUNITSYMBOL, rp.SALESUNITSYMBOL, rp.PURCHASEUNITSYMBOL, rp.PRODUCTNUMBER, rp.PRODUCTSEARCHNAME, rp.DATAAREAID  from InventTableModule itm
inner join ECORESRELEASEDPRODUCTV2ENTITY rp on itm.ITEMID = rp.ITEMNUMBER and itm.DATAAREAID = rp.DATAAREAID
where rp.INVENTORYUNITSYMBOL = ''


Update itm
	set itm.UnitId = 'ea'
from InventTableModule itm
inner join ECORESRELEASEDPRODUCTV2ENTITY rp on itm.ITEMID = rp.ITEMNUMBER and itm.DATAAREAID = rp.DATAAREAID
where rp.INVENTORYUNITSYMBOL = ''

--3 PURCHASEUNITSYMBOL
select itm.ITEMID, itm.UNITID, itm.DATAAREAID, rp.ITEMNUMBER, rp.INVENTORYUNITSYMBOL, rp.SALESUNITSYMBOL, rp.PURCHASEUNITSYMBOL, rp.PRODUCTNUMBER, rp.PRODUCTSEARCHNAME, rp.DATAAREAID  from InventTableModule itm
inner join ECORESRELEASEDPRODUCTV2ENTITY rp on itm.ITEMID = rp.ITEMNUMBER and itm.DATAAREAID = rp.DATAAREAID
where rp.PURCHASEUNITSYMBOL = '' and rp.INVENTORYUNITSYMBOL != ''


Update itm
	set itm.UnitId = rp.INVENTORYUNITSYMBOL
from InventTableModule itm
inner join ECORESRELEASEDPRODUCTV2ENTITY rp on itm.ITEMID = rp.ITEMNUMBER and itm.DATAAREAID = rp.DATAAREAID
where rp.PURCHASEUNITSYMBOL = '' and rp.INVENTORYUNITSYMBOL != ''


--4 SALESUNITSYMBOL
select itm.ITEMID, itm.UNITID, itm.DATAAREAID, rp.ITEMNUMBER, rp.INVENTORYUNITSYMBOL, rp.SALESUNITSYMBOL, rp.PURCHASEUNITSYMBOL, rp.PRODUCTNUMBER, rp.PRODUCTSEARCHNAME, rp.DATAAREAID  from InventTableModule itm
inner join ECORESRELEASEDPRODUCTV2ENTITY rp on itm.ITEMID = rp.ITEMNUMBER and itm.DATAAREAID = rp.DATAAREAID
where rp.SALESUNITSYMBOL = '' and rp.INVENTORYUNITSYMBOL != ''
 

Update itm
	set itm.UnitId = rp.INVENTORYUNITSYMBOL
from InventTableModule itm
inner join ECORESRELEASEDPRODUCTV2ENTITY rp on itm.ITEMID = rp.ITEMNUMBER and itm.DATAAREAID = rp.DATAAREAID
where rp.SALESUNITSYMBOL = '' and rp.INVENTORYUNITSYMBOL != ''


--5  It's not supposed to be UOM = '1'
select unitid, ITEMID,DATAAREAID from INVENTTABLEMODULE
where  itemId = '92039' and DATAAREAID = 'usrt'

update INVENTTABLEMODULE
	set UnitId = 'ea'
where  itemId = '92039' and DATAAREAID = 'usrt'


--6 %20 issue in the PrimaryVendorAccountNumber field  (not sure that it works)
select it.ITEMID, it.DATAAREAID, it.PRIMARYVENDORID, LEN(it.PRIMARYVENDORID) from INVENTTABLE it
where it.PRIMARYVENDORID = ''

update INVENTTABLE
	set PRIMARYVENDORID = N''
where PRIMARYVENDORID = ''

--7 Remove {"} symbol from Item Names and Descriptions
Update EcoResProductTranslation 
Set 
    Name = LEFT(REPLACE(Name, '"',''''''), 60),
    Description = LEFT(REPLACE(Name, '"',''''''), 1000)
where name LIKE '%"%' or description LIKE '%"%'
