select VENDORACCOUNTNUMBER, INVOICEVENDORACCOUNTNUMBER from VENDVENDORV2ENTITY 
where VENDORACCOUNTNUMBER = INVOICEVENDORACCOUNTNUMBER


update VENDVENDORV2ENTITY 
	set INVOICEVENDORACCOUNTNUMBER = ''
where VENDORACCOUNTNUMBER = INVOICEVENDORACCOUNTNUMBER

--2
select ACCOUNTNUM, DATAAREAID, INVOICEACCOUNT from VENDTABLE
where INVOICEACCOUNT != ''
